<a href="https://colab.research.google.com/github/ouissem11/App-pratique/blob/master/9-13/question3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
#importation des bases de données
df=pd.read_csv('/content/ProjetsComplet.csv')
df.columns

Index(['Unnamed: 0', 'Finess', 'Nom de l'établissement', 'NomInvestigateur',
       'PrénomInvestigateur', 'TitreProjet', 'NuméroProjet', 'Acronyme',
       'MontantAccordé', 'Année', 'Type', 'Projet'],
      dtype='object')

In [3]:
df.columns = ["Unnamed: 0","Finess","Nomdeletablissement","NomInvestigateur","PrenomInvestigateur","TitreProjet","NumeroProjet","Acronyme","MontantAccorde","Annee","Type",
"Projet"]

In [4]:
df=df.loc[:,['Annee', 'MontantAccorde','Nomdeletablissement','Projet']]
df

      Annee MontantAccorde        Nomdeletablissement Projet
0      2012       156091.0               CHU D'ANGERS   PHRC
1      2012       110000.0                       APHM   PHRC
2      2012       200000.0  ASSISTANCE PUBLIQUE AP-HP   PHRC
3      2012       112000.0  ASSISTANCE PUBLIQUE AP-HP   PHRC
4      2012        60836.0              CHRU DE BREST   PHRC
...     ...            ...                        ...    ...
2943   2021         415822  ASSISTANCE PUBLIQUE AP-HP    PRT
2944   2021       307134.6              CHRU DE TOURS    PRT
2945   2021     838 426 €#  ASSISTANCE PUBLIQUE AP-HP    PRT
2946   2021     324 700 €¤  ASSISTANCE PUBLIQUE AP-HP    PRT
2947   2021     224 389 €¤            CHU MONTPELLIER    PRT

[2948 rows x 4 columns]

In [5]:
df2018=df[df.Annee == 2018]
df2018

      Annee MontantAccorde           Nomdeletablissement Projet
1450   2018         196804                 CHU DE RENNES   PHRC
1451   2018         222520                  CHU D'ANGERS   PHRC
1452   2018         295791      CHU HOPITAUX DE BORDEAUX   PHRC
1453   2018         296880     ASSISTANCE PUBLIQUE AP-HP   PHRC
1454   2018         294442                    CHU AMIENS   PHRC
...     ...            ...                           ...    ...
2740   2018       249730.0  CLCC INSTITUT GUSTAVE ROUSSY    PRT
2741   2018       129813.0                         AP-HP    PRT
2742   2018       170009.0            CENTRE LEON BERARD    PRT
2743   2018       491459.0      INSTITUT CLAUDIUS REGAUD    PRT
2744   2018       286152.0                           HCL    PRT

[307 rows x 4 columns]

In [6]:
df2018[pd.to_numeric(df2018.MontantAccorde, errors='coerce').isnull()]

Empty DataFrame
Columns: [Annee, MontantAccorde, Nomdeletablissement, Projet]
Index: []

In [7]:
df2018['MontantAccorde'] = df2018['MontantAccorde'].astype(float, errors = 'raise')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [8]:
df2018.dtypes

Annee                    int64
MontantAccorde         float64
Nomdeletablissement     object
Projet                  object
dtype: object

In [9]:
df2018['MontantAccorde'] = pd.to_numeric(df2018['MontantAccorde'])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [10]:
df2018=df2018.groupby(['Nomdeletablissement','Annee']).sum()['MontantAccorde']
df2018

Nomdeletablissement                      Annee
ADMINISTRATION GENERALE DU CHR DE REIMS  2018     2.888370e+05
AP-HM                                    2018     1.378254e+06
AP-HP                                    2018     3.090226e+07
APHM                                     2018     3.347402e+06
ASSISTANCE PUBLIQUE AP-HP                2018     7.000000e+06
                                                      ...
INSTITUT BERGONIE                        2018     2.974930e+05
INSTITUT CLAUDIUS REGAUD                 2018     2.256925e+06
INSTITUT DE CANCEROLOGIE DE L'OUEST      2018     4.851154e+05
INSTITUT MUTUALISTE MONTSOURIS           2018     3.400000e+05
INSTITUT PAOLI CALMETTES                 2018     5.602650e+05
Name: MontantAccorde, Length: 73, dtype: float64

In [11]:
df2018= df2018.reset_index()

In [12]:
df2018=df2018.sort_values('MontantAccorde', ascending = False).head(10)
df2018

          Nomdeletablissement  Annee  MontantAccorde
2                       AP-HP   2018      30902264.9
61                        HCL   2018       7085318.9
4   ASSISTANCE PUBLIQUE AP-HP   2018       7000000.0
41            CHU MONTPELLIER   2018       5724964.4
39                  CHU LILLE   2018       5398073.0
35                  CHU DIJON   2018       4388338.0
47                 CHU RENNES   2018       3437963.2
3                        APHM   2018       3347402.1
43                 CHU NANTES   2018       3191368.4
51               CHU TOULOUSE   2018       3102618.0

In [13]:
#bdd 2019 tope 10
df2019=df[df.Annee == 2019]
df2019

      Annee MontantAccorde                    Nomdeletablissement Projet
1679   2019         282925                        CHU DE TOULOUSE   PHRC
1680   2019         296508                              CHU DIJON   PHRC
1681   2019         247103                            CHU DE NICE   PHRC
1682   2019         166510        CENTRE FRANCOIS BACLESSE - CAEN   PHRC
1683   2019         295729  HOPITAUX UNIVERSITAIRES DE STRASBOURG   PHRC
...     ...            ...                                    ...    ...
2760   2019       326074.0           CLCC INSTITUT GUSTAVE ROUSSY    PRT
2761   2019       580050.0                    CLCC INSTITUT CURIE    PRT
2762   2019        69400.0                     CENTRE LEON BERARD    PRT
2763   2019       185921.0                          CHU DE RENNES    PRT
2764   2019       251137.0                                    HUS    PRT

[337 rows x 4 columns]

In [14]:
df2019[pd.to_numeric(df2019.MontantAccorde, errors='coerce').isnull()]

Empty DataFrame
Columns: [Annee, MontantAccorde, Nomdeletablissement, Projet]
Index: []

In [15]:
df2019['MontantAccorde'] = df2019['MontantAccorde'].astype(float, errors = 'raise')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [16]:
df2019.dtypes

Annee                    int64
MontantAccorde         float64
Nomdeletablissement     object
Projet                  object
dtype: object

In [17]:
df2019=df2019.groupby(['Nomdeletablissement','Annee']).sum()['MontantAccorde']
df2019

Nomdeletablissement                    Annee
AP-HP                                  2019     36098609.0
APHM                                   2019      3453887.0
APHM DIRECTION GENERALE                2019      2545286.0
ASSISTANCE PUBLIQUE AP-HP              2019      5601647.0
ASSISTANCE PUBLIQUE-HOPITAUX DE PARIS  2019      5502428.0
                                                   ...
INSTITUT DE CANCEROLOGIE DE L'OUEST    2019       715079.0
INSTITUT DE CANCEROLOGIE DE LORRAINE   2019       280238.0
INSTITUT PAOLI CALMETTES               2019      1105971.0
LES HOPITAUX DE SAINT-MAURICE          2019       150500.0
MAISON MEDICALE JEANNE GARNIER         2019       845232.0
Name: MontantAccorde, Length: 84, dtype: float64

In [18]:
 df2019= df2019.reset_index()

In [19]:
df2019=df2019.sort_values('MontantAccorde', ascending = False).head(10)
df2019

                      Nomdeletablissement  Annee  MontantAccorde
0                                   AP-HP   2019      36098609.0
29                           CHU BORDEAUX   2019       5652971.0
3               ASSISTANCE PUBLIQUE AP-HP   2019       5601647.0
4   ASSISTANCE PUBLIQUE-HOPITAUX DE PARIS   2019       5502428.0
47               CHU HOPITAUX DE BORDEAUX   2019       4538151.0
49                        CHU MONTPELLIER   2019       4195202.0
59                           CHU TOULOUSE   2019       3467022.0
1                                    APHM   2019       3453887.0
57                              CHU ROUEN   2019       3296094.0
46                           CHU GRENOBLE   2019       3101889.0

In [24]:
import matplotlib.pyplot as plt

In [25]:
import plotly.express as px

In [36]:
fig = px.bar(df2018, x="Nomdeletablissement", y ="MontantAccorde",
             hover_data =[ "Nomdeletablissement"],
             color="MontantAccorde",
             title ="Top 10 des montants acorrdés en 2018" )

In [35]:
fig

In [37]:
fig = px.bar(df2019, x="Nomdeletablissement", y ="MontantAccorde",
             hover_data =[ "Nomdeletablissement"],
             color="MontantAccorde",
            title ="Top 10 des montants acorrdés en 2019" )

In [38]:
fig